language: java
addons:
  sonarcloud:
    organization: revaturelabs
    token:
      secure: qYbaDW3C25EMSw1i5ZjP5yttL9zUwKtZ0b2jR1itiTFsDdO7GcL/e8DSwVmU/zK9t5ouktUOn0J8w9Zx+GCJCi8LqyMggkXbq2bUft5EoIHm7C0GSJV/77RIt8IWEp99j1z28+MdbuDex2s4TZydOOs27+n44iglcAe+9oTy5j0WcYCp0vmFeNreSnD5azGTJSpz1VkynEQzDDUHFco/V02aw/yQ4uyWNo8FJWVH634NoEYjeqyPRWevX4wUihLeasBPYttd7AlL20mrhVG62zOr45FijNyMqCLkP2pfhigq8Z72617d1CSPp8LLMlQkKFRR/i6AxXKHokbQjENzhimwBA2vxGOH+fqKOkcqL6X5UrxSehdp+dz+Vi+CXU46CvpR4PL554AzdpvpXKwHpCD7cySU1o1DFH50eyBet6xLjCshpHxmEB+RquEgpGRaby8rIo5edDAjdqh6ngo0JgrMgBx3Ax3UDIIA2DIu9/TgAVc2pK+aaBdqQjcLKejFMh30cqqMH6AgPixeSCnrAMiLrGpSNhhXYxZ122JipKMytiGFPdgLV6zsSlQy8+Qcbxgn47jT1ttz95w1iW+mR6n+PVfZNRNQe04etBPmcYocKife1c2/CqyDi7+90Mka5Z9UvvWA4pr10sLF+MgLQuZZQLY/yxfWXiYVaFibCFg=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: EGJwDLkHoQRewBiCCHesMNi75g3gpMFEaQM0nsiklLengGxaoFR3w1DuAtIeNdxBWdrkkx3y9WVMLpPR1ffK1os61GISkwWsZPdiWuQRiRHihKJEXGebO0Hw6OBULG3644EF4CoOohZuQIK/v8CDOMUMf/HEyzcLQZXFHsDQKTPNG81C+yhxIOB0wtMBv2pcT4LIcbC6ehDEw5MLVG3XB8X8nFLzRs50CA+1QdwMMG5FNGxtNvKFOfxelEkPLVYKXc4zzDg7PE1/Z73wFRpih3aVcmm3MVpYnt8t7lnjDeBo/cDKlDsCAFuYHmr5Er9XlbsP3tAv1/xMx4E6HMSvJyc42hStqZC83aRX6PP0N9tQGXDJm1LStdW6IaDfHddZkLBUs8V2qwvPmBmP6EG3ZcJV0UdrDP1DQCU7AzJmx2hzu8OyDjt9uJvaVYqNjACFhanPjKIP45mwaunGUEDBHUzGEorYzokj3NVdgDNJEX45xkbxT8xD3HMrOif8jWfgTVwZ+kmY/Hbf+T2SRuxKrPFm7walixNVaEhvI0bZkkhJ36W0sZHpTQdbKXkqbyRt4kjUwMAtb8RSUKpVYyO/H/a2c7wRH5tFrg2BCwh2LMKl0tpqoKXC6wofg6HJ8IsvFsDIwLzqmbFxG8UuGT1HbhV9aOJViYRhyEuulkfVtAg=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-unavailable-service
    branch: develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
