spring:
  application:
    name: unavailable
  cloud:
    services:
      registrationMethod: direct
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    leaseRenewalIntervalInSeconds: 10
    healthcheck:       
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

server:
  servlet:
    contextPath: /v0

