spring:
  profiles:
    active: production

---

spring:
  profiles: production
  application:
    name: unavailable
  cloud:
    services:
      registrationMethod: direct
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    leaseRenewalIntervalInSeconds: 10
    healthcheck:       
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

server:
  servlet:
    contextPath: /v0

---

spring:
  profiles: test
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    listener:
      simple:
        auto-startup: false
eureka:
  client:
    enabled: false
management:
  health:
    rabbit:
      enabled: false
security:
  basic:
    enabled: false
